### ISSUE TITLE
build: move dev postinstall

### ISSUE THREAD

**Issue by gabisinhas** [carbon-design-system/carbon-components-vue#1616] opened 2024-07-24 13:28 UTC
## Title line template: [Title]: Brief description

Bug:

hi team, I am facing this error when trying to install carbon-vue in a new project using Node20/npm10.
It is related to closed issue - https://github.com/carbon-design-system/carbon-components-vue/pull/1611

![image](https://github.com/user-attachments/assets/5cc491ab-d8f5-4ba3-b49c-d2ecd28e04e9)

> What version of the Carbon Design System are you using?
    "@carbon/icons-vue": "^10.83.1",
    "@carbon/vue": "^2.45.1",

**Comment by davidnixon** [comment] 2024-07-25 19:56
This is different than #1576 since above you say `"@carbon/vue": "^2.45.1"`
I don't think node 20 will work with vue 2. The lastest try to fix this for Vue 3 is in flight in #1617

**Comment by davidnixon** [comment] 2024-07-25 19:59
Can you confirm which version of vue you are using?
The error above with the "...Cannot find ... devPreinstall.js" looks like Vue 3

**Comment by gabisinhas** [comment] 2024-07-25 20:39
@davidnixon  I am using     "vue": "^3.4.31",

**Comment by davidnixon** [comment] 2024-07-26 16:25
awesome. was worried it was still Vue 2 :-)
I am closing this as a dupe of #1576.
I merged PR #1616 just now and a build is running to publish 3.0.19 hopefully that fixes it.

**Closed by davidnixon** 2024-07-26 16:25 UTC
