### ISSUE TITLE
Add support for SSR

### ISSUE THREAD

**Issue by kieusonlam** [carbon-design-system/carbon-components-vue#643] opened 2019-10-27 09:18 UTC
Any consider to support SSR in the feautures? I'm using Nuxt.js by the way?

**Comment by lee-chase** [comment] 2019-10-28 10:57
I am unaware of anything preventing the use of SSR in this component library. Please ask document any issue you are having. 

See
https://vuejs.org/v2/guide/ssr.html

**Comment by kieusonlam** [comment] 2019-10-28 11:13
@lee-chase I pretty sure you can't.

Here is the simplest example https://codesandbox.io/s/nuxt-carbon-5b8qe

**Comment by lee-chase** [comment] 2019-10-28 14:24
Not sure why but the example you put together crashes my browser and having only played with nuxt I'm not in the best place to try and get something working on code sandbox.

I did just note the following, which could have an effect, not certain without setting up a project to try these things out. Feel free to have a crack at determining what changes, if any, we would need to make to the library.

"It is important to know that in any Vue instance lifecycle, only beforeCreate and created hooks are called both, from client-side and server-side. All other hooks are called only from the client-side."

**Comment by lee-chase** [comment] 2019-10-29 10:19
NOTE: Creating a nuxt example on codesandbox, adding the following causes codesandbox to hang.

plugins/carbon.js
```js
import Vue from "vue";
import "carbon-components/css/carbon-components.css";
import CarbonComponentsVue from "@carbon/vue";
Vue.use(CarbonComponentsVue);
```

nuxt.config.js
```js
plugins: ["@/plugins/carbon"],
```

**Comment by lee-chase** [comment] 2019-11-04 13:07
Worth a glance if you're taking on this issue
https://blog.lichter.io/posts/universal-ssr-vue-component-guide/

**Comment by kieusonlam** [comment] 2019-11-04 13:21
I guess so, but i already tried to put `typeof window !== 'undefined'` on every place using document on this project, I still got build problem. Not sure if i did anything wrong.

**Comment by gaabrielcs** [comment] 2019-11-04 14:28
Found me into the same problem, after debugging a lot I found that the problem is in the build. When I clone the repository and change the vue-config to use `css.extract: true` it generated a new bundle without the css in the javascript, I replaced the files in my project node_modules folder with the new ones and it worked. I still didn't test all the components to see if any of them have a side effect because of the change I made, but the button and accordion are working fine.

**Comment by lee-chase** [comment] 2019-11-04 15:17
That strikes me as an issue with nuxt @gaabrielcs might be worth taking a look through nuxt issues.

**Comment by gaabrielcs** [comment] 2019-11-04 15:59
I think its whether the lib is build to work with SSR or not, as the build creates somehow the css inside the js using the `window.document` without checking it for undefined, when Nuxt tries to use the lib on the server it gives an error because the `document` doesn't exist on the server, so what I think is that the lib has to be built with this compatibility. I know that nuxt could provide a way to render better this scenario, but doing what I said in the previous comment could be an easier and faster fix that helps us to provide the SSR for the users of the lib.

**Comment by lee-chase** [comment] 2019-11-04 17:06
https://stackoverflow.com/questions/54472124/vue-cli-build-a-lib-ssr-css-issue

**Comment by lee-chase** [comment] 2019-11-06 18:15
@gaabrielcs @kieusonlam give it another go with 2.18.0-canary.0

https://codesandbox.io/s/codesandbox-nuxt-9sr07

**Comment by gaabrielcs** [comment] 2019-11-06 20:24
@lee-chase Tested on my project and in a blank one, and looks like it is working.

**Comment by lee-chase** [comment] 2019-11-11 16:00
Released in 2.18.0

**Closed by lee-chase** 2019-11-11 16:00 UTC
Labels: enhancement

**Comment by humanistical** [comment] 2019-11-11 16:57
I'm getting this in the sandbox you sent out, which is the same error I'm seeing trying to use ssr with 2.18.0:
![image](https://user-images.githubusercontent.com/14792421/68605427-fd8e5300-0471-11ea-8520-6fa75122f558.png)

**Comment by lee-chase** [comment] 2019-11-11 17:46
Sorry @humanistical there seemed to be an issues using the ES version of the bee, perhaps due to needing babel. Switched to using lib version and all seems well.

**Comment by humanistical** [comment] 2019-11-13 20:54
Yes! Changing my icons to lib version fixed it. Thank you!

**Comment by lee-chase** [comment] 2020-11-25 11:18
A better codepen https://codesandbox.io/s/infallible-glade-pxf68?file=/styles/_carbon.scss
