### ISSUE TITLE
<cv-date-picker> ReferenceError: Cannot access 'props' before initialization

### ISSUE THREAD

**Issue by krko12345** [carbon-design-system/carbon-components-vue#1549] opened 2023-10-24 19:34 UTC
CvDatePicker is throwing error during execution:

![image](https://github.com/carbon-design-system/carbon-components-vue/assets/36237241/d685b6a6-58d0-4a6a-8458-0e9b23d8460d)

Seems like it is related to these lines:

![image](https://github.com/carbon-design-system/carbon-components-vue/assets/36237241/f2ccdfc8-5e4d-4fdf-a5cb-a12ac44a73be)

If modified the @carbon/.../CvDatePicker.vue component, and move the highlighted lines behind the 'props' object definition, then it works fine. Can you please fix this asap in the package?

**Comment by davidnixon** [comment] 2023-12-08 19:28
The change makes sense but I cannot reproduce the error. My editor also thinks its an issue:
![image](https://github.com/carbon-design-system/carbon-components-vue/assets/7536103/34181fab-3e71-4206-bb17-78a01735048c)

**Comment by davidnixon** [comment] 2024-01-23 23:20
Fixed in 3.0.12

**Closed by davidnixon** 2024-01-23 23:20 UTC
Labels: PR opened
