### ISSUE TITLE
reopen of #542 

### ISSUE THREAD

**Issue by naftali-ibm** [carbon-design-system/carbon-components-vue#858] opened 2020-03-31 14:13 UTC
few month after fixing of bug #542 -  it is now happen again:
I don't remember how is was last time, but now it is jump both ways, means  - if I scrolled down and pressing the menu of the first row, it is jumping up and when I did  scroll and clicking the menu of the one of the lowest rows it is jumping up even if the row I clocked on is not even visible!

## What package(s) are you using?
2.23.2

- [X] `carbon-components`
- [ ] `carbon-components-react`

## Detailed description

> Describe in detail the issue you're having.
cv-data-table (which is bigger than the screen and need to scroll down to see lower rows) and when overflow-menu clicked the whole table “jumped” up to the first row.
> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to
> see changed?

> What browser are you working in?
all
> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we
> should be aware of?

## Steps to reproduce the issue

1. Step one
open page with a table larger than the screen
2. Step two
scroll down 
3. Step three
press overflow menu - the table jump to the first line

> Please create a reduced test case in CodeSandbox
>
> - Style and vanilla JS:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/components/examples/codesandbox
> - React:
>   https://codesandbox.io/s/github/carbon-design-system/carbon/tree/master/packages/react/examples/codesandbox

## Additional information

- Screenshots or code
- Notes

**Comment by lee-chase** [comment] 2020-04-01 11:16
Struggling again to re-create this @naftali-ibm can you give me a precise set of steps, perhaps a browser.

https://codepen.io/naftali-ibm/pen/MWgPypB

**Comment by lee-chase** [comment] 2020-04-17 14:36
Unable to reproduce, will close if no example provided.

**Comment by lee-chase** [comment] 2020-04-24 15:45
Closing as unable to reproduce.

**Closed by lee-chase** 2020-04-24 15:45 UTC
