### ISSUE TITLE
Input label click does not focus input

### ISSUE THREAD

**Issue by bleush38p** [carbon-design-system/carbon-components-vue#515] opened 2019-08-23 15:23 UTC
## Detailed description

Clicking on the label of an input (text input, number input, text area, etc.) does not cause the input field to gain focus as expected.

With the vanilla components, clicking on a label appears to focus the associated field ([Text input](https://codepen.io/team/carbon/full/EJKNOw/), for example). But the Vue, Angular, and React components do not have the same behavior.

Vanilla:
![vanilla](https://user-images.githubusercontent.com/7422958/63603639-a9b94f80-c58f-11e9-9e85-326c42156143.gif)

Vue:
![vue](https://user-images.githubusercontent.com/7422958/63603786-edac5480-c58f-11e9-9b40-28773daf1994.gif)

**Comment by lee-chase** [comment] 2019-09-02 16:00
Seems to work here in codepen https://codepen.io/lee-chase/pen/XWreNOw

Is it possible the problem is with storybook or do you have an example outside of storybook?

**Comment by lee-chase** [comment] 2019-09-10 17:00
Closing as storybook issue

**Closed by lee-chase** 2019-09-10 17:00 UTC
